services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: testfilm
    ports:
      - "8889:3306"

  web:
    depends_on:
      - db
    image: php:7.4-apache
    environment:
      - ALLOW_OVERRIDE=true
    working_dir: /var/www/html
    ports:
      - "8081:80"
    volumes:
      - /home/userp/Documents/dockers/testfilm/vhosts/:/etc/apache2/sites-enabled
      - /home/userp/Documents/dockers/testfilm/_inc/:/var/www/html
  
