services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: testfilm
    ports:
      - '8889:3306'

  web:
    depends_on:
      - db
    image: pensiero/apache-php-mysql:php7.4
    environment:
      - ALLOW_OVERRIDE=true
    working_dir: /var/www/html
    ports:
      - '8081:80'
    volumes:
      - /home/user01/testfilm/vhosts/:/etc/apache2/sites-enabled
      - /home/user01/testfilm/_inc/:/var/www/html
  test:
    image: ssh-test
    volumes:
      - ~/.ssh:/home/user01/.ssh:ro
